### ISSUE TITLE
bad_wifi executed if wifi not connected at library start

### ISSUE THREAD

**Issue by kevinkk525** [peterhinch/micropython-iot#13]
I guess this is a minor issue in the real application but if you are trying stuff and the microcontroller happens to be disconnected from the wifi, bad_wifi will be executed although it would just need to connect to the wifi as the credentials are stored.
Not sure if this should be fixed or just added to the README.

**Comment by peterhinch** [comment]
So you're suggesting:
```python
    async def _run(self, loop):
        s = self._sta_if
        s.connect()
        # rest of code
```
Seems reasonable.

**Comment by kevinkk525** [comment]
I just checked the behaviour of connect() with wrong credentials and it seems reasonable to try to connect at program start. With wrong credentials it just tries to connect to the network ever second.
Don't know how it reacts with no credentials stored.
