### ISSUE TITLE
[Improvement] allow my_id to be not new-line terminated

### ISSUE THREAD

**Issue by kevinkk525** [peterhinch/micropython-iot#14]
By simply changing this line in the client.py constructor the library could support not new-line terminated ids:
`self.my_id = my_id if my_id.endswith("\n") else my_id+"\n"`

In my opinion this would improve compatibility as you typically don't have new-line terminated id strings if you use them in other parts of your application too. 
If you happen to forget to the new-line termination, the whole library acts crazy, although it sometimes works as the next keepalive provides the new-line termination for the id.

**Comment by peterhinch** [comment]
Will do.
