### ISSUE TITLE
If first message is dupe it won't be recognized

### ISSUE THREAD

**Issue by kevinkk525** [peterhinch/micropython-iot#15]
If the first message (after the ID) is received twice, it won't be recognized because self._init in this line is True and mid does not get added to the bytearray:
`if self._init or not mid or isnew(mid):`

Every message afterwards will get correctly recognized.

How to reproduce:
Send two message with mid=0 after each other after sending the id.

**Comment by peterhinch** [comment]
Thank you. The **self._init** bound variable is evidently cruft from an earlier iteration where the first received message would otherwise have been lost.

Deleting the variable and all references to it works, and should fix the problem.

**Comment by kevinkk525** [comment]
Think so too.

**Comment by kevinkk525** [comment]
I was wrong closing this so early. It does not fix the whole problem.
```
                if not mid:
                    isnew(-1)  # Clear down rx message record
                # _init : client has restarted. mid == 0 server power up
                if self._init or not mid or isnew(mid):
```
This means, that if the client receives a message with mid==0, the bytearray will get reset, so the duplicate message with mid==0 will reset it again and the library will never recognize a duplicate message with id==0. 
So the fix could be to initialize isnew(-1) at the start of the _reader and make the server reset it too on reconnect.

**Comment by kevinkk525** [comment]
Also the line 
`if not mid or isnew(mid):`
would need to be changed to
`if isnew(mid):`
so that the mid 0 will get added to the bytearray.

**Comment by peterhinch** [comment]
I'm not sure that will fix it. The first message would have been sent before the outage. **.reader()**  would then be canceled and restarted. It would fail to recognise the dupe.

I think after an outage we need to do the following, in **._run().** If the last received **mid** was zero we don't need to clear the generator as that must be its only contents. Otherwise we clear it down.

What do you think?

**Comment by kevinkk525** [comment]
Mine hurts now too. Will think about it again tomorrow. Forgot that the first message after an outage is already a dupe and possibly more than one message after an outage so only storing the last mid wouldn't solve it.
