### ISSUE TITLE
No direct bytes transmission support with new-line termination

### ISSUE THREAD

**Issue by kevinkk525** [peterhinch/micropython-iot#17]
I know this may be a tough topic as it basically can't even be changed without integrating header support into the library and changing the way it receives and sends messages.

I try to explain my problem:
If you want to send a bytes object without converting it, you can easily end up sending an object with a new-line termination. This is especially problematic if you try to bring in a header support.
Let's take this bytearray as an example:
`a=bytearray(b'\n\x03"\x00\x00')`
The new-line character represents the message-id 10.
Now if I send this header, it will be split because of the new-line character. 
I can however convert it first to a string representation and then convert it to json but that would implicate a huge overhead on performance and RAM.
The other option would be to convert the hex representation to an actual integer like 125129825 which can be re-converted using the struct module. Works but also has quite some overhead on performance, transmission length and RAM and is not dynamic, the header would have to have a fixed length.

The solution to this would be to implement a header support for every message containing at least these information: mid, len of the message, use-case (e.g. keepalive, ACK)
Then the library can just read those 4-5 bytes from the socket, figure out the length of the message and then receive the missing bytes. Then a newline-termination as sign of the end of the transmission is possible, however with ACK messages this is not needed as the socket will be empty until the client sends the ACK back.

So I'm basically asking you, if you would consider changing the protocol in that way or not. If not, my header support branch would be quite different, which I would like to prevent. 
Implementing the header on top of the library would be an even bigger waste of resources so I'm not really considering this an option.
Changing the header format in any way is better than building on top of the library but still a huge waste of resources and that's why I wanted header support in the first place.
But even outside of header support, the current implementation of the library does not support a reliable way of sending bytes/bytearrays that some people might be interested in.

I published my header fork just now, in case you would like to have a look at it. Latest changes of master are not pulled yet: [header](https://github.com/kevinkk525/micropython-iot/tree/header)

**Comment by peterhinch** [comment]
It was never the intention to support binary data as this can always include '\n' characters. While I appreciate you've fixed this it significantly increases the complexity of **client.py**. If anything I'd like to find ways to trim it down so that it can be compiled natively. I can't say I'm keen on this.

There are good ways of encoding binary data at the application level. 
[Base64](https://en.wikipedia.org/wiki/Base64) comes to mind, but there are others.

**Comment by kevinkk525** [comment]
I completely understand. We have different goals here and that's fine.

There are ways but most of them are quite costly. Converting a bytearray using ubinascii on an esp8266 is however an acceptable way for short bytes and I'll probably go for that as the overhead is only about 1ms and doubles the length.
