### ISSUE TITLE
Asynchronous HTTPs requests

### ISSUE THREAD

**Issue by niclascrane** [peterhinch/micropython-iot#21]
Hi, 
on my wipy, I need to implement a bridge, which connects the UART port with a Server and send the message back via UART.
So i created three looping tasks:
- READ_UART: Reading in Data from UART and writes to the queue READ_queue
- PROCESS_FRAME: waits for READ_queue and sends the frame with a "https Post message" to a server.
The respond is then sent to a WRITE_queue
- WRITE_UART: waits for WRITE_QUEUE and sends data via UART.

Makes this approach sense?
What is the best way to make GET,PUT,POST.. requests on https asynchronously? I had a look at uaiohttps but i can not get it running. I used MicroRESTCli and it worked, but i think that this is not an asynchronous approach. 
Also, i need to authorize first with a user and password to get a token for further communication.

Thanks so much in advance!

**Comment by kevinkk525** [comment]
Sorry but what does this have to do with the library here?
Please ask your question on the micropython forum.

**Comment by peterhinch** [comment]
Indeed. I'm closing this.
