### ISSUE TITLE
One message_id generator for all server clients

### ISSUE THREAD

**Issue by kevinkk525** [peterhinch/micropython-iot#22]
https://github.com/peterhinch/micropython-iot/blob/c081425ef37784fa3856014940e52b247c6ceeb1/server.py#L34
The server currently uses one message_id generator for all clients instead of one generator per client.

**Comment by peterhinch** [comment]
That is a very good point. I don't see significant practical consequences but it's clearly wrong.

 Thank you. Will fix.
