### ISSUE TITLE
Server needs tx flow control

### ISSUE THREAD

**Issue by kevinkk525** [peterhinch/micropython-iot#24]
In my short test when merging our functionality I came across the problem that the client received too many message and drops some. This happens if you use multiple concurrent writes on the server.
Therefore there should be a flow control only allowing a message to be sent every 50ms(?) to give the client time to process the message.

**Comment by peterhinch** [comment]
Hi Kevin - I'm tied up on something else so it may be a few days before I get to look at the iot stuff. 

Just to let you know my latest changes to client.py (not yet pushed) have added a software WDT.

I have had very rare instances of unexplained crashes. These could have an electrical cause.

My test of the WDT was to run the ESP8266 from a USB phone charger battery, then to connect the battery to a USB charger. When the battery was fully charged I disconnected the USB charger. In the past this **always** crashed the ESP. In my test it rebooted and ran.

**Comment by kevinkk525** [comment]
Ok, no problem. I'll keep testing the resilience. Thanks for letting me know.

Interesting, so you experienced esp crashes too. A software WDT is a good idea, I run one anyway as the lolin nodemcu are not the most stable ones.

**Comment by peterhinch** [comment]
I'm not sure about this. It would be easy to implement - just hold the lock in **._vwrite**. 

However there is a case for documenting the issue and warn the user against launching multiple write coros in quick succession. The physical capabilities of clients may vary (I'm thinking Pyboard D series here). Also the risk of overloading the client may depend on the size of the messages as well as their frequency.

**Comment by kevinkk525** [comment]
holding the lock in ._vwrite would delay the calling coroutine which is why I'd not recommend it in comparison to delaying the calling coroutine of the next message but it is a possibility to solve the problem.

If you plan to support multiple devices, it may be interesting to send a configuration additionally to the client_id so the server can be configured for different device types.
