### ISSUE TITLE
Wifi error due to indentation error

### ISSUE THREAD

**Issue by kevinkk525** [peterhinch/micropython-iot#28]
I believe in lines 93-95 in client.py the indentation is wrong and would only initialize the wifi correctly if wdog is False.
```
else:
            self._feed = lambda x: None

            self._sta_if = network.WLAN(network.STA_IF)
            ap = network.WLAN(network.AP_IF)  # create access-point interface
            ap.active(False) # deactivate the interface
```
When it should be:
```
else:
            self._feed = lambda x: None

self._sta_if = network.WLAN(network.STA_IF)
ap = network.WLAN(network.AP_IF)  # create access-point interface
ap.active(False) # deactivate the interface
```

**Comment by peterhinch** [comment]
Thank you - I don't know how that happened. Now pushing an update.

**Comment by kevinkk525** [comment]
You had Port conditional code there and just removed the conditional checks without correcting the indentation. I think that's what happened.

**Comment by kevinkk525** [comment]
PS don't forget to update your .mpy too

**Comment by peterhinch** [comment]
Good point - I'll need to check compatibility too: I rather think the mpy format has changed so I may need to check out an earlier cross compiler.

**Comment by peterhinch** [comment]
OK, I've now updated the mpy and added a version warning in the docs. I've also added a note to explain how to build the right version for the release build, in case you want to do it: might save you a bit of research :)

**Comment by kevinkk525** [comment]
That is awesome, thanks a lot!
Have been running into that issue yesterday when my new .mpy files didn't work with the few days old esp32 fimware build. This will surely save me some research :)
