### ISSUE TITLE
UDP support?

### ISSUE THREAD

**Issue by skylin008** [peterhinch/micropython-iot#29]
Thank you shared this impressive project.From the detail protocol content describe " keep alive ", it use the TCP protocol yet? But it can be used the UDP protocl.Thanks!

**Comment by peterhinch** [comment]
The links between the nodes and the server PC use a simple socket connection. If you need to interface between the server PC and the internet you can use any protocol you choose: the PC can run CPython so you can use any of the standard libraries for this purpose.
