### ISSUE TITLE
Connection not "ok" if server does not send anything except keepalive

### ISSUE THREAD

**Issue by kevinkk525** [peterhinch/micropython-iot#3]
When trying to build a new server application I encountered the following problem:

The client connects and sends keepalives. 
The server accepts and sends keepalives.
The client sends his id, server accepts it but does not answer.
Client.ok variable never gets true, although the led keeps flashing because of the keepalive.

Now according to the code of _readline, a flashing led should mean that cl.ok is True:
```
        while True:
            if line.endswith(b'\n'):
                self.ok = True  # Got at least 1 packet
                if len(line) > 1:
                    return line
                line = b''
                start = utime.ticks_ms()  # Blank line is keepalive
                if self.led is not None:
                    self.led(not self.led())
            d = self.sock.readline()
```

I actually have no idea why it behaves this way. Must have slipped myself. Hopefully you can find the problem as it would require the server to actually answer with a real message, not just with a keepalive. I don't think you intended it to be this way.

Same thing happens with your server application. Just comment out the writer loop and the client application will never start sending anything because cl.ok won't be True.

Once you manage to get cl.ok=True then it works and sends everything. Even if the connection breaks down and it does not get cl.ok=True afterwards, it will still send new messages despite the state of cl.ok.
In your example it just does not start because you check that state first.

**Comment by peterhinch** [comment]
Well spotted but I think that's a bug I fixed a few days ago.

I should warn that there is a minor API change in the works. This affects the server side only, namely args to `server.run()`. Instead the number of connections the function now expects a `set` containing the `client_id`'s of the expected clients. This enables checks to be made for unexpected or duplicate clients.

It also facilitates a `server.wait_all()` coro, where a server-side application coro pauses on startup until all expected clients have connected. This is the main reason for the change: in applications where clients communicate with each other, the server-side application needs to "know" that all clients have made initial connections.

The current `s_comms_cp.py` does this at application level which is clunky. The new version simply waits on the above function before proceeding.

**Comment by kevinkk525** [comment]
Yeah should have checked my source file on the microcontroller first. With the new version including your fix it is working just fine.

That sounds interesting, thanks for letting me know. Will implement something similar in my server application. I don't use any of your server code by now. My approach however is more dynamic, creating clients as they connect. No need to know which clients will connect.
